### ISSUE TITLE
getAngularSpeed() fails when over 360 degrees

### ISSUE THREAD

**Issue by RobTillaart** [RobTillaart/AS5600#14]
```cpp
  int      angle   = readAngle();
  uint32_t deltaT  = now - _lastMeasurement;
  int      deltaA  = angle - _lastAngle;   //  fails mod 360
```
 if lastAngle == 355 and angle == 2  the deltaA should be 7 not -353

Need a construction that takes into account that we do not know if the thing runs CW or CCW.

To be investigated a.s.a.p  so it can be part of 0.2.0

**Comment by Shdwdrgn** [comment]
Testing this with the updated code in the develop branch from 5 hours ago, I think this one is resolved.  I spun the magnet back and forth across the 359/0 degree threshold multiple times and the values from getAngularSpeed() remained generally consistent within the limitations of my manual movements.

**Comment by RobTillaart** [comment]
Thanks for testing this one too
