### ISSUE TITLE
Weird noise in cumulative position reading

### ISSUE THREAD

**Issue by cranefist** [RobTillaart/AS5600#34]
I have this weird noise on the cumulative position output:

![image](https://user-images.githubusercontent.com/35430692/236680788-95841c9d-d319-40f5-9805-f112eb94ee36.png)

![image](https://user-images.githubusercontent.com/35430692/236680933-0777b430-3bc0-4dd4-8d98-89f21c61ea02.png)

The output is :

readAngle() / rawAngle()
getCumulativePosition()

Also, it seems you are using rawAngle output for the cumulativeposition, wouldn't it be better to use the filtered readAngle output? So i could choose the filter settings? Now my filter settings have no effect on the cumulative output.

EDIT:
I think the problem was starting a task pinned to core on ESP32, when i started the task without pinning it to a core..  the noise is gone. Ill investigate more and close this issue later if this was the actual cause.

Though i still recommend using readAngle, instead of rawAngle on the cumulative output. Especially the hysteris might be good, as without it there is the possibility of bouncing between 0 and 4095 and that could F up the revolutions counter.

**Comment by RobTillaart** [comment]
Thanks for this issue,
Think I understand the point you make.
Quite busy so will try to look into this coming week.

**Comment by cranefist** [comment]
Ok, ill keep investigating this. As your library now uses the exact same code i was using for the cumulative position. Ill try to see if i get the same noise using my old code.

Really nice that you added it btw. Simplified things a lot.

The noise is still there, its really weird. I thought i solved it, but nope. And that noise cant come from the unfiltered raw output. As i dont see the same noise on that output.

**Comment by RobTillaart** [comment]
> wouldn't it be better to use the filtered readAngle output? 
So i could choose the filter settings? 
Now my filter settings have no effect on the cumulative output.

Think it would be better, need to read the data sheet again if there are reasons pro/con.

Note: Would also need to change **resetCumulativePosition()**
It would bring code in line with **getAngularSpeed()** which uses **readAngle()** too.

**Comment by cranefist** [comment]
Ok, good that you mentioned that resetCumulative also needed to be changed, i now switched to the filtered output and will see how it goes.

I did have some issues of values bouncing and the turn point. That can really reek havoc. I remember when i was at this same problem with you at some point, when i was trying to figure out why i was missing points at the turn around point. And its exactly the hysteresis, and its there for a purpose.

I use these both for motors, and dials. So for dials i want to use max slow filters so they are as smooth as possible. And for motors faster filters for fastest possible output.

**Comment by RobTillaart** [comment]
Merged and released 0.3.7.
So you should now be able to use the filters, 
If there are still problems feel free to reopen this issue (or open a new topic)
