### ISSUE TITLE
Use lib without dir pin

### ISSUE THREAD

**Issue by bar2104y** [RobTillaart/AS5600#42]
In some projects dir pin is permanently connected to GND or 5V. Method begin need to set dir pin. How use lib in this case?

**Comment by RobTillaart** [comment]
Just do not set the direction pin in **begin()**.
It will set a default of SW controlled direction.
If the default direction is OK, you do not need to do anything, otherwise you may just change it once.
(Or swap the GND for 5V or 5V for GND)

Does this help?

**Comment by bar2104y** [comment]
Yes. I try it, it work for me.

Thank you!
