### ISSUE TITLE
AS5600.h Library , trouble with a second sensor

### ISSUE THREAD

**Issue by laptophead** [RobTillaart/AS5600#49]
I am trying to implement 2 sensors on the same IC2 bus. I bought the one called AS5600L that has an address of 0x40. Tried to implement it using setAddress, but the library won't execute it.
Says there is no member. Please help.
Mitch

AS5600_position_M_01_TwoSensors:27:11: error: 'class AS5600' has no member named 'setAddress'; did you mean 'getAddress'?
   as5600L.setAddress(0x40);  // AS5600L only

**Comment by RobTillaart** [comment]
This discussion is continued in #48
So I close this one.
