### ISSUE TITLE
resetCumulativePosition not correct if direction set

### ISSUE THREAD

**Issue by Chris-42** [RobTillaart/AS5600#69]
if one uses software direction the reset function for cummulative Position is not working.
in line 507 instead of using
`  _lastPosition = readReg2(AS5600_RAW_ANGLE) & 0x0FFF;`
it should be
`  _lastPosition = readAngle();`

**Comment by RobTillaart** [comment]
Thanks for testing, appreciated.

Will dive into it tomorrow, looks more of the "same problem"

**Comment by RobTillaart** [comment]
@Chris-42 
Develop branch is build,
Please give it a try

**Comment by RobTillaart** [comment]
So the reset cumulative position now works.

GetAngularSpeed()
On update is false it returns the last calculated speed.

You can verify this by calling it once with true and second time with false.

Wrt your question, I want to find a form that is backwards compatible as the library is downloaded and forked a lot (>6x day).

To be continued.

**Comment by Chris-42** [comment]
think this is fixed

**Comment by RobTillaart** [comment]
Will merge the fix for this one into version 0.6.3 first.
